// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: grid.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BasisType int32

const (
	BasisType_LINEAR    BasisType = 0
	BasisType_QUADRATIC BasisType = 1
)

// Enum value maps for BasisType.
var (
	BasisType_name = map[int32]string{
		0: "LINEAR",
		1: "QUADRATIC",
	}
	BasisType_value = map[string]int32{
		"LINEAR":    0,
		"QUADRATIC": 1,
	}
)

func (x BasisType) Enum() *BasisType {
	p := new(BasisType)
	*p = x
	return p
}

func (x BasisType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BasisType) Descriptor() protoreflect.EnumDescriptor {
	return file_grid_proto_enumTypes[0].Descriptor()
}

func (BasisType) Type() protoreflect.EnumType {
	return &file_grid_proto_enumTypes[0]
}

func (x BasisType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BasisType.Descriptor instead.
func (BasisType) EnumDescriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{0}
}

type BuildType int32

const (
	BuildType_SEQUENTIAL BuildType = 0
	BuildType_PARALLEL   BuildType = 1
)

// Enum value maps for BuildType.
var (
	BuildType_name = map[int32]string{
		0: "SEQUENTIAL",
		1: "PARALLEL",
	}
	BuildType_value = map[string]int32{
		"SEQUENTIAL": 0,
		"PARALLEL":   1,
	}
)

func (x BuildType) Enum() *BuildType {
	p := new(BuildType)
	*p = x
	return p
}

func (x BuildType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildType) Descriptor() protoreflect.EnumDescriptor {
	return file_grid_proto_enumTypes[1].Descriptor()
}

func (BuildType) Type() protoreflect.EnumType {
	return &file_grid_proto_enumTypes[1]
}

func (x BuildType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildType.Descriptor instead.
func (BuildType) EnumDescriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{1}
}

type FormulaType int32

const (
	FormulaType_SIMPLE FormulaType = 0
	FormulaType_DIFFUR FormulaType = 1
)

// Enum value maps for FormulaType.
var (
	FormulaType_name = map[int32]string{
		0: "SIMPLE",
		1: "DIFFUR",
	}
	FormulaType_value = map[string]int32{
		"SIMPLE": 0,
		"DIFFUR": 1,
	}
)

func (x FormulaType) Enum() *FormulaType {
	p := new(FormulaType)
	*p = x
	return p
}

func (x FormulaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormulaType) Descriptor() protoreflect.EnumDescriptor {
	return file_grid_proto_enumTypes[2].Descriptor()
}

func (FormulaType) Type() protoreflect.EnumType {
	return &file_grid_proto_enumTypes[2]
}

func (x FormulaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormulaType.Descriptor instead.
func (FormulaType) EnumDescriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{2}
}

type Point2D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point2D) Reset() {
	*x = Point2D{}
	mi := &file_grid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point2D) ProtoMessage() {}

func (x *Point2D) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point2D.ProtoReflect.Descriptor instead.
func (*Point2D) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{0}
}

func (x *Point2D) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point2D) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Grid2DRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormulaX      string                 `protobuf:"bytes,1,opt,name=formula_x,json=formulaX,proto3" json:"formula_x,omitempty"`
	FormulaY      string                 `protobuf:"bytes,2,opt,name=formula_y,json=formulaY,proto3" json:"formula_y,omitempty"`
	Min           *Point2D               `protobuf:"bytes,3,opt,name=min,proto3" json:"min,omitempty"`
	Max           *Point2D               `protobuf:"bytes,4,opt,name=max,proto3" json:"max,omitempty"`
	Eps           float64                `protobuf:"fixed64,5,opt,name=eps,proto3" json:"eps,omitempty"`
	BuildType     BuildType              `protobuf:"varint,6,opt,name=build_type,json=buildType,proto3,enum=grid.BuildType" json:"build_type,omitempty"`
	BasisType     BasisType              `protobuf:"varint,7,opt,name=basis_type,json=basisType,proto3,enum=grid.BasisType" json:"basis_type,omitempty"`
	AnchorPoints  []*Point2D             `protobuf:"bytes,8,rep,name=anchor_points,json=anchorPoints,proto3" json:"anchor_points,omitempty"`
	Step          *float64               `protobuf:"fixed64,9,opt,name=step,proto3,oneof" json:"step,omitempty"`
	FormulaType   FormulaType            `protobuf:"varint,10,opt,name=formula_type,json=formulaType,proto3,enum=grid.FormulaType" json:"formula_type,omitempty"`
	MaxLevel      int32                  `protobuf:"varint,11,opt,name=max_level,json=maxLevel,proto3" json:"max_level,omitempty"`
	MaxNodesInDim int64                  `protobuf:"varint,12,opt,name=max_nodes_in_dim,json=maxNodesInDim,proto3" json:"max_nodes_in_dim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grid2DRequest) Reset() {
	*x = Grid2DRequest{}
	mi := &file_grid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grid2DRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grid2DRequest) ProtoMessage() {}

func (x *Grid2DRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grid2DRequest.ProtoReflect.Descriptor instead.
func (*Grid2DRequest) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{1}
}

func (x *Grid2DRequest) GetFormulaX() string {
	if x != nil {
		return x.FormulaX
	}
	return ""
}

func (x *Grid2DRequest) GetFormulaY() string {
	if x != nil {
		return x.FormulaY
	}
	return ""
}

func (x *Grid2DRequest) GetMin() *Point2D {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *Grid2DRequest) GetMax() *Point2D {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *Grid2DRequest) GetEps() float64 {
	if x != nil {
		return x.Eps
	}
	return 0
}

func (x *Grid2DRequest) GetBuildType() BuildType {
	if x != nil {
		return x.BuildType
	}
	return BuildType_SEQUENTIAL
}

func (x *Grid2DRequest) GetBasisType() BasisType {
	if x != nil {
		return x.BasisType
	}
	return BasisType_LINEAR
}

func (x *Grid2DRequest) GetAnchorPoints() []*Point2D {
	if x != nil {
		return x.AnchorPoints
	}
	return nil
}

func (x *Grid2DRequest) GetStep() float64 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *Grid2DRequest) GetFormulaType() FormulaType {
	if x != nil {
		return x.FormulaType
	}
	return FormulaType_SIMPLE
}

func (x *Grid2DRequest) GetMaxLevel() int32 {
	if x != nil {
		return x.MaxLevel
	}
	return 0
}

func (x *Grid2DRequest) GetMaxNodesInDim() int64 {
	if x != nil {
		return x.MaxNodesInDim
	}
	return 0
}

type Grid2D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Grid2D_Node2D       `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	EntryPoints   []*Grid2D_Node2D       `protobuf:"bytes,2,rep,name=entry_points,json=entryPoints,proto3" json:"entry_points,omitempty"`
	Min           *Point2D               `protobuf:"bytes,3,opt,name=min,proto3" json:"min,omitempty"`
	Max           *Point2D               `protobuf:"bytes,4,opt,name=max,proto3" json:"max,omitempty"`
	BasisType     BasisType              `protobuf:"varint,5,opt,name=basis_type,json=basisType,proto3,enum=grid.BasisType" json:"basis_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grid2D) Reset() {
	*x = Grid2D{}
	mi := &file_grid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grid2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grid2D) ProtoMessage() {}

func (x *Grid2D) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grid2D.ProtoReflect.Descriptor instead.
func (*Grid2D) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{2}
}

func (x *Grid2D) GetNodes() []*Grid2D_Node2D {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Grid2D) GetEntryPoints() []*Grid2D_Node2D {
	if x != nil {
		return x.EntryPoints
	}
	return nil
}

func (x *Grid2D) GetMin() *Point2D {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *Grid2D) GetMax() *Point2D {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *Grid2D) GetBasisType() BasisType {
	if x != nil {
		return x.BasisType
	}
	return BasisType_LINEAR
}

type Grid2D_Index2D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             uint64                 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint64                 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grid2D_Index2D) Reset() {
	*x = Grid2D_Index2D{}
	mi := &file_grid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grid2D_Index2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grid2D_Index2D) ProtoMessage() {}

func (x *Grid2D_Index2D) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grid2D_Index2D.ProtoReflect.Descriptor instead.
func (*Grid2D_Index2D) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Grid2D_Index2D) GetX() uint64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Grid2D_Index2D) GetY() uint64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Grid2D_GridKey2D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *Grid2D_Index2D        `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Level         *Grid2D_Index2D        `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grid2D_GridKey2D) Reset() {
	*x = Grid2D_GridKey2D{}
	mi := &file_grid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grid2D_GridKey2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grid2D_GridKey2D) ProtoMessage() {}

func (x *Grid2D_GridKey2D) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grid2D_GridKey2D.ProtoReflect.Descriptor instead.
func (*Grid2D_GridKey2D) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Grid2D_GridKey2D) GetIndex() *Grid2D_Index2D {
	if x != nil {
		return x.Index
	}
	return nil
}

func (x *Grid2D_GridKey2D) GetLevel() *Grid2D_Index2D {
	if x != nil {
		return x.Level
	}
	return nil
}

type Grid2D_Node2D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Grid2D_GridKey2D      `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CenterUnit    *Point2D               `protobuf:"bytes,2,opt,name=center_unit,json=centerUnit,proto3" json:"center_unit,omitempty"`
	Alpha         *Point2D               `protobuf:"bytes,3,opt,name=alpha,proto3" json:"alpha,omitempty"`
	HasChildren   bool                   `protobuf:"varint,4,opt,name=has_children,json=hasChildren,proto3" json:"has_children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grid2D_Node2D) Reset() {
	*x = Grid2D_Node2D{}
	mi := &file_grid_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grid2D_Node2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grid2D_Node2D) ProtoMessage() {}

func (x *Grid2D_Node2D) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grid2D_Node2D.ProtoReflect.Descriptor instead.
func (*Grid2D_Node2D) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Grid2D_Node2D) GetKey() *Grid2D_GridKey2D {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Grid2D_Node2D) GetCenterUnit() *Point2D {
	if x != nil {
		return x.CenterUnit
	}
	return nil
}

func (x *Grid2D_Node2D) GetAlpha() *Point2D {
	if x != nil {
		return x.Alpha
	}
	return nil
}

func (x *Grid2D_Node2D) GetHasChildren() bool {
	if x != nil {
		return x.HasChildren
	}
	return false
}

var File_grid_proto protoreflect.FileDescriptor

const file_grid_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"grid.proto\x12\x04grid\"%\n" +
	"\aPoint2D\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\xcf\x03\n" +
	"\rGrid2DRequest\x12\x1b\n" +
	"\tformula_x\x18\x01 \x01(\tR\bformulaX\x12\x1b\n" +
	"\tformula_y\x18\x02 \x01(\tR\bformulaY\x12\x1f\n" +
	"\x03min\x18\x03 \x01(\v2\r.grid.Point2DR\x03min\x12\x1f\n" +
	"\x03max\x18\x04 \x01(\v2\r.grid.Point2DR\x03max\x12\x10\n" +
	"\x03eps\x18\x05 \x01(\x01R\x03eps\x12.\n" +
	"\n" +
	"build_type\x18\x06 \x01(\x0e2\x0f.grid.BuildTypeR\tbuildType\x12.\n" +
	"\n" +
	"basis_type\x18\a \x01(\x0e2\x0f.grid.BasisTypeR\tbasisType\x122\n" +
	"\ranchor_points\x18\b \x03(\v2\r.grid.Point2DR\fanchorPoints\x12\x17\n" +
	"\x04step\x18\t \x01(\x01H\x00R\x04step\x88\x01\x01\x124\n" +
	"\fformula_type\x18\n" +
	" \x01(\x0e2\x11.grid.FormulaTypeR\vformulaType\x12\x1b\n" +
	"\tmax_level\x18\v \x01(\x05R\bmaxLevel\x12'\n" +
	"\x10max_nodes_in_dim\x18\f \x01(\x03R\rmaxNodesInDimB\a\n" +
	"\x05_step\"\x96\x04\n" +
	"\x06Grid2D\x12)\n" +
	"\x05nodes\x18\x01 \x03(\v2\x13.grid.Grid2D.Node2DR\x05nodes\x126\n" +
	"\fentry_points\x18\x02 \x03(\v2\x13.grid.Grid2D.Node2DR\ventryPoints\x12\x1f\n" +
	"\x03min\x18\x03 \x01(\v2\r.grid.Point2DR\x03min\x12\x1f\n" +
	"\x03max\x18\x04 \x01(\v2\r.grid.Point2DR\x03max\x12.\n" +
	"\n" +
	"basis_type\x18\x05 \x01(\x0e2\x0f.grid.BasisTypeR\tbasisType\x1a%\n" +
	"\aIndex2D\x12\f\n" +
	"\x01x\x18\x01 \x01(\x04R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x04R\x01y\x1ac\n" +
	"\tGridKey2D\x12*\n" +
	"\x05index\x18\x01 \x01(\v2\x14.grid.Grid2D.Index2DR\x05index\x12*\n" +
	"\x05level\x18\x02 \x01(\v2\x14.grid.Grid2D.Index2DR\x05level\x1a\xaa\x01\n" +
	"\x06Node2D\x12(\n" +
	"\x03key\x18\x01 \x01(\v2\x16.grid.Grid2D.GridKey2DR\x03key\x12.\n" +
	"\vcenter_unit\x18\x02 \x01(\v2\r.grid.Point2DR\n" +
	"centerUnit\x12#\n" +
	"\x05alpha\x18\x03 \x01(\v2\r.grid.Point2DR\x05alpha\x12!\n" +
	"\fhas_children\x18\x04 \x01(\bR\vhasChildren*&\n" +
	"\tBasisType\x12\n" +
	"\n" +
	"\x06LINEAR\x10\x00\x12\r\n" +
	"\tQUADRATIC\x10\x01*)\n" +
	"\tBuildType\x12\x0e\n" +
	"\n" +
	"SEQUENTIAL\x10\x00\x12\f\n" +
	"\bPARALLEL\x10\x01*%\n" +
	"\vFormulaType\x12\n" +
	"\n" +
	"\x06SIMPLE\x10\x00\x12\n" +
	"\n" +
	"\x06DIFFUR\x10\x012=\n" +
	"\vGridService\x12.\n" +
	"\tGetGrid2D\x12\x13.grid.Grid2DRequest\x1a\f.grid.Grid2DB\x0eZ\fDiplom/protob\x06proto3"

var (
	file_grid_proto_rawDescOnce sync.Once
	file_grid_proto_rawDescData []byte
)

func file_grid_proto_rawDescGZIP() []byte {
	file_grid_proto_rawDescOnce.Do(func() {
		file_grid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grid_proto_rawDesc), len(file_grid_proto_rawDesc)))
	})
	return file_grid_proto_rawDescData
}

var file_grid_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_grid_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grid_proto_goTypes = []any{
	(BasisType)(0),           // 0: grid.BasisType
	(BuildType)(0),           // 1: grid.BuildType
	(FormulaType)(0),         // 2: grid.FormulaType
	(*Point2D)(nil),          // 3: grid.Point2D
	(*Grid2DRequest)(nil),    // 4: grid.Grid2DRequest
	(*Grid2D)(nil),           // 5: grid.Grid2D
	(*Grid2D_Index2D)(nil),   // 6: grid.Grid2D.Index2D
	(*Grid2D_GridKey2D)(nil), // 7: grid.Grid2D.GridKey2D
	(*Grid2D_Node2D)(nil),    // 8: grid.Grid2D.Node2D
}
var file_grid_proto_depIdxs = []int32{
	3,  // 0: grid.Grid2DRequest.min:type_name -> grid.Point2D
	3,  // 1: grid.Grid2DRequest.max:type_name -> grid.Point2D
	1,  // 2: grid.Grid2DRequest.build_type:type_name -> grid.BuildType
	0,  // 3: grid.Grid2DRequest.basis_type:type_name -> grid.BasisType
	3,  // 4: grid.Grid2DRequest.anchor_points:type_name -> grid.Point2D
	2,  // 5: grid.Grid2DRequest.formula_type:type_name -> grid.FormulaType
	8,  // 6: grid.Grid2D.nodes:type_name -> grid.Grid2D.Node2D
	8,  // 7: grid.Grid2D.entry_points:type_name -> grid.Grid2D.Node2D
	3,  // 8: grid.Grid2D.min:type_name -> grid.Point2D
	3,  // 9: grid.Grid2D.max:type_name -> grid.Point2D
	0,  // 10: grid.Grid2D.basis_type:type_name -> grid.BasisType
	6,  // 11: grid.Grid2D.GridKey2D.index:type_name -> grid.Grid2D.Index2D
	6,  // 12: grid.Grid2D.GridKey2D.level:type_name -> grid.Grid2D.Index2D
	7,  // 13: grid.Grid2D.Node2D.key:type_name -> grid.Grid2D.GridKey2D
	3,  // 14: grid.Grid2D.Node2D.center_unit:type_name -> grid.Point2D
	3,  // 15: grid.Grid2D.Node2D.alpha:type_name -> grid.Point2D
	4,  // 16: grid.GridService.GetGrid2D:input_type -> grid.Grid2DRequest
	5,  // 17: grid.GridService.GetGrid2D:output_type -> grid.Grid2D
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_grid_proto_init() }
func file_grid_proto_init() {
	if File_grid_proto != nil {
		return
	}
	file_grid_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grid_proto_rawDesc), len(file_grid_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grid_proto_goTypes,
		DependencyIndexes: file_grid_proto_depIdxs,
		EnumInfos:         file_grid_proto_enumTypes,
		MessageInfos:      file_grid_proto_msgTypes,
	}.Build()
	File_grid_proto = out.File
	file_grid_proto_goTypes = nil
	file_grid_proto_depIdxs = nil
}
