// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: grid.proto

package gridProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GridService_GetGrid2D_FullMethodName = "/grid.GridService/GetGrid2D"
)

// GridServiceClient is the client API for GridService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GridServiceClient interface {
	GetGrid2D(ctx context.Context, in *Grid2DRequest, opts ...grpc.CallOption) (*Grid2D, error)
}

type gridServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGridServiceClient(cc grpc.ClientConnInterface) GridServiceClient {
	return &gridServiceClient{cc}
}

func (c *gridServiceClient) GetGrid2D(ctx context.Context, in *Grid2DRequest, opts ...grpc.CallOption) (*Grid2D, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Grid2D)
	err := c.cc.Invoke(ctx, GridService_GetGrid2D_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GridServiceServer is the server API for GridService service.
// All implementations must embed UnimplementedGridServiceServer
// for forward compatibility.
type GridServiceServer interface {
	GetGrid2D(context.Context, *Grid2DRequest) (*Grid2D, error)
	mustEmbedUnimplementedGridServiceServer()
}

// UnimplementedGridServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGridServiceServer struct{}

func (UnimplementedGridServiceServer) GetGrid2D(context.Context, *Grid2DRequest) (*Grid2D, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGrid2D not implemented")
}
func (UnimplementedGridServiceServer) mustEmbedUnimplementedGridServiceServer() {}
func (UnimplementedGridServiceServer) testEmbeddedByValue()                     {}

// UnsafeGridServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GridServiceServer will
// result in compilation errors.
type UnsafeGridServiceServer interface {
	mustEmbedUnimplementedGridServiceServer()
}

func RegisterGridServiceServer(s grpc.ServiceRegistrar, srv GridServiceServer) {
	// If the following call panics, it indicates UnimplementedGridServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GridService_ServiceDesc, srv)
}

func _GridService_GetGrid2D_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Grid2DRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServiceServer).GetGrid2D(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GridService_GetGrid2D_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServiceServer).GetGrid2D(ctx, req.(*Grid2DRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GridService_ServiceDesc is the grpc.ServiceDesc for GridService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GridService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grid.GridService",
	HandlerType: (*GridServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGrid2D",
			Handler:    _GridService_GetGrid2D_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grid.proto",
}
