# Конфигурационный файл nginx для проксирования трафика

events {
    worker_connections 1024;
}

http {
    # Определение upstream для gRPC сервера
    upstream grpc_backend {
        server server:50051;  # Предполагаем, что контейнер с сервером будет доступен по имени 'server'
    }

    # Сервер, слушающий HTTP/2 трафик (обычно на порту 443 или 80)
    server {
        listen 80 http2;  # Используем HTTP/2 для gRPC
        
        # Проксирование всех запросов к gRPC серверу
        location / {
            grpc_pass grpc://grpc_backend;
            # Дополнительные настройки проксирования при необходимости
        }
    }
}