# docker-compose.yml для настройки подъема сервера и nginx

services:
  # Сервис gRPC сервера
  server:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    container_name: grid_service
    ports:
      - "9999:9999"  # Открываем порт для прямого доступа к серверу (опционально)
    networks:
      - app_network
    restart: unless-stopped

  envoy:
    image: envoyproxy/envoy:v1.33-latest
    container_name: envoy
    volumes:
      - ../envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8082:8082"
    networks:
      - app_network
    command: [ "-c", "/etc/envoy/envoy.yaml", "--service-cluster", "grpc-web-proxy" ]
    depends_on:
      - grid_service
    restart: unless-stopped


# Определение сети для взаимодействия между сервисами
networks:
  app_network:
    driver: bridge