# docker-compose.yml для настройки подъема сервера и nginx

services:
  # Сервис gRPC сервера
  server:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    container_name: server
    ports:
      - "9999:9999"  # Открываем порт для прямого доступа к серверу (опционально)
    networks:
      - app_network
    restart: unless-stopped

  envoy:
    image: envoyproxy/envoy:v1.33-latest
    container_name: envoy
    volumes:
      - ../envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8082:8082"
    networks:
      - app_network
    command: [ "-c", "/etc/envoy/envoy.yaml", "--service-cluster", "grpc-web-proxy" ]
    depends_on:
      - server
    restart: unless-stopped

  web:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.web
    container_name: flutter_web
    ports:
      - "80:80"
    networks:
      - app_network
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - app_network
    depends_on:
      - prometheus
    restart: unless-stopped

# Определение сети для взаимодействия между сервисами
volumes:
  grafana_data:

networks:
  app_network:
    driver: bridge